/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ADrawer: typeof import('ant-design-vue/es')['Drawer']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AModal: typeof import('ant-design-vue/es')['Modal']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    MDEditor: typeof import('./src/components/MDEditor/index.vue')['default']
    MDHeader: typeof import('./src/components/MDHeader/index.vue')['default']
    MDView: typeof import('./src/components/MDView/index.vue')['default']
    Panel: typeof import('./src/components/Panel/index.vue')['default']
  }
}
